#!/usr/bin/env bash
set -e

# Extract the first vless/vmess/trojan URL from config.dae
NODE=$(awk -F'"' '/(vless|vmess|trojan|trojan-go|ss|ssr|socks5|http):\/\// {print $2; exit}' config.dae)

if [ -z "$NODE" ]; then
    echo "Error: no proxy node found in config.dae"
    exit 1
fi

# Generate a temporary Go file that sets embeddedNode
cat > cmd/embedded_node.go <<EOF
// Code generated by build_inline.sh; DO NOT EDIT.
package cmd

func init() {
    embeddedNode = "$NODE"
}
EOF

# Build static binary
CGO_ENABLED=0 go build -ldflags='-s -w' -o gg_static_inline .

# Clean up temporary file
rm cmd/embedded_node.go

echo "Built: gg_static_inline (embedded node: ${NODE:0:60}...)"
